Repository tazjin/nixery, pull requests merged in 2019-08, with the labels that each got.

#17 Note that the demo instance is just a demo
  static/index.html
Labels: documentation

#22 fix(nix): Support retrieving differently cased top-level attributes
  build-registry-image.nix
Labels: enhancement

#26 Minor fixes to README after new website release
  README.md
Labels: documentation

#28 fix(go): Fix breakage in unsigned URLs
  main.go
Labels: bug

#34 Add an integration test that runs on Travis
  .travis.yml
Labels: enhancement

#37 Add iana-etc and cacert to the shell convenience package
  server/builder/builder.go
Labels: enhancement

#40 docs(README): Update links to layering strategy
  README.md
Labels: documentation

#41 Sort requested packages in image name & spec
  server/builder/builder.go
Labels: enhancement
